### ISSUE TITLE
Visual Query over connect-sdk

### ISSUE THREAD

**Issue by Timon-IW** [i2group/analyze-connect-node-sdk#26] opened 2024-08-22 10:33 UTC
Greetings,

I had a strange Problem with the Implementation of a visual query search on the example-connector.
I have just added one with the addVisualQueryService function, but if I try to use it, the button "edit structure" won't work.
Neither in i2notebook nor in the Analyst's Notebook. It just does nothing.
If I create a new connector and add one there, it works.
I couldn't find any reason why it should not work with the example-connector.

This is not really an issue with that I need help, but I wanted to let you know that there is a problem if someone tries to expand on what you provide.

If there is simply something that needs to be reconfigured that I overlooked, please let me know.

Best regards,
Timon Brunnert

**Comment by Anthony-Johnson-i2** [comment] 2024-08-22 10:37
Hi @Timon-IW 

Thank you for bringing this to our attention.
I will pass this on to our development team and see what they have to say on the matter.

Cheers

**Comment by Jonny-Cornwell-i2** [comment] 2024-09-07 07:38
Him @Timon-IW,

Sorry for the delay. I am able to reproduce this so I'll close this and raise something internal to track this as it'll need some more investigation to find the cause.

Thanks for reporting it!

**Closed by Jonny-Cornwell-i2** 2024-09-07 07:38 UTC
